# Generated by Django 3.1.4 on 2021-01-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatStateFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cat_state_feature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'rel_project_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelProjectFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'rel_project_feature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'rel_project_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('picpathdada', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('backend', models.CharField(max_length=50)),
                ('frontend', models.CharField(max_length=50)),
                ('repo_name', models.CharField(max_length=100)),
                ('repo_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-title'],
                'managed': True,
            },
        ),
    ]
