# Generated by Django 3.1.4 on 2021-01-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('backend', models.CharField(max_length=50)),
                ('frontend', models.CharField(max_length=50)),
                ('repo_name', models.CharField(max_length=100)),
                ('repo_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'projecto',
                'ordering': ['-title'],
                'managed': True,
            },
        ),
    ]
